package propra.com.sml.programacion.practicas.entregas.febrero7.ejercicio4;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class Ex4Graphics extends JFrame implements ActionListener {
	private static final int HEIGHT = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
	private static final int WIDTH = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
	private static final long serialVersionUID = 1L;
	private Font northSouthFont = new Font("Verdana", Font.BOLD, WIDTH/120);
	private Font eastCenterFont = new Font("Verdana", Font.BOLD, WIDTH/90);
	private Font westCenterFont = new Font("Verdana", Font.BOLD, WIDTH/150);
	private Font centerButtonFont = new Font("Verdana", Font.BOLD, WIDTH/70);
	JButton buyButton = new JButton("Comprar");
	JButton sellButton = new JButton("Vender");
	JButton helpButton = new JButton("Ayuda");
	JButton infoButton = new JButton("Info");
	JButton exitButton = new JButton("Exit");
	public Ex4Graphics() {
		setResizable(false);
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
		setLayout(new BorderLayout());
		setUndecorated(true);
		setExtendedState(MAXIMIZED_BOTH);
		createNorth();
		createCenter();
		createSouth();
		setVisible(true);
	}
	public void initBlank(JTextField field) {
		field.setEditable(false);
		field.setBackground(this.getBackground());
		field.setBorder(null);
	}
	public void createNorth() {
		JPanel north = new JPanel(new GridLayout(2,2));
		JTextField northLeftText = new JTextField();
		JTextField northRightText = new JTextField();
		JTextField blank = new JTextField();
		JTextField blank2 = new JTextField();
		JTextField blank3 = new JTextField();
		JTextField blank4 = new JTextField();
		JTextField blank5 = new JTextField();
		northLeftText.setFont(northSouthFont);
		northLeftText.setText("     Nombre del Club: "+Club.getClubName());
		northRightText.setFont(northSouthFont);
		northRightText.setText("Dinero disponible: "+Club.getClubMoney()+"€     ");
		northRightText.setHorizontalAlignment(SwingConstants.RIGHT);
		initBlank(northRightText);
		initBlank(northLeftText);
		initBlank(blank);
		initBlank(blank2);
		initBlank(blank3);
		initBlank(blank4);
		initBlank(blank5);
		north.add(northLeftText);
		north.add(blank);
		north.add(blank2);
		north.add(northRightText);
		north.add(blank3);
		north.add(blank4);
		north.add(blank5);
		add(north,BorderLayout.NORTH);
	}
	public void createCenter() {
		JPanel center = new JPanel(new GridLayout(1,3));
		center.add(createEastLabels());
		center.add(createCenterButtons());
		center.add(createWestLabels());
		add(center,BorderLayout.CENTER);
	}
	public JPanel createEastLabels() {
		JPanel east = new JPanel(new GridLayout(13,1));
		JTextField team = new JTextField("     Plantilla");
		JTextField player1 = new JTextField("          Jugador");
		JTextField player2 = new JTextField("          Jugador");
		JTextField player3 = new JTextField("          Jugador");
		JTextField player4 = new JTextField("          Jugador");
		JTextField player5 = new JTextField("          Jugador");
		JTextField player6 = new JTextField("          Jugador");
		JTextField player7 = new JTextField("          Jugador");
		JTextField player8 = new JTextField("          Jugador");
		JTextField player9 = new JTextField("          Jugador");
		JTextField player10 = new JTextField("          Jugador");
		JTextField player11 = new JTextField("          Jugador");
		JTextField blank = new JTextField();
		team.setFont(eastCenterFont);
		player1.setFont(eastCenterFont);
		player2.setFont(eastCenterFont);
		player3.setFont(eastCenterFont);
		player4.setFont(eastCenterFont);
		player5.setFont(eastCenterFont);
		player6.setFont(eastCenterFont);
		player7.setFont(eastCenterFont);
		player8.setFont(eastCenterFont);
		player9.setFont(eastCenterFont);
		player10.setFont(eastCenterFont);
		player11.setFont(eastCenterFont);
		initBlank(team);
		initBlank(player1);
		initBlank(player2);
		initBlank(player3);
		initBlank(player4);
		initBlank(player5);
		initBlank(player6);
		initBlank(player7);
		initBlank(player8);
		initBlank(player9);
		initBlank(player10);
		initBlank(player11);
		initBlank(blank);
		east.add(team);
		east.add(player1);
		east.add(player2);
		east.add(player3);
		east.add(player4);
		east.add(player5);
		east.add(player6);
		east.add(player7);
		east.add(player8);
		east.add(player9);
		east.add(player10);
		east.add(player11);
		east.add(blank);
		return east;
	}
	public JPanel createWestLabels() {
		JPanel west = new JPanel(new GridLayout(26,1));
		JTextField avaliable = new JTextField("Jugadores Disponibles");
		JTextField player1 = new JTextField("Jugador");
		JTextField player2 = new JTextField("Jugador");
		JTextField player3 = new JTextField("Jugador");
		JTextField player4 = new JTextField("Jugador");
		JTextField player5 = new JTextField("Jugador");
		JTextField player6 = new JTextField("Jugador");
		JTextField player7 = new JTextField("Jugador");
		JTextField player8 = new JTextField("Jugador");
		JTextField player9 = new JTextField("Jugador");
		JTextField player10 = new JTextField("Jugador");
		JTextField player11 = new JTextField("Jugador");
		JTextField player12 = new JTextField("Jugador");
		JTextField player13 = new JTextField("Jugador");
		JTextField player14 = new JTextField("Jugador");
		JTextField player15 = new JTextField("Jugador");
		JTextField player16 = new JTextField("Jugador");
		JTextField player17 = new JTextField("Jugador");
		JTextField player18 = new JTextField("Jugador");
		JTextField player19 = new JTextField("Jugador");
		JTextField player20 = new JTextField("Jugador");
		JTextField player21 = new JTextField("Jugador");
		JTextField player22 = new JTextField("Jugador");
		JTextField player23 = new JTextField("Jugador");
		JTextField player24 = new JTextField("Jugador");
		JTextField player25 = new JTextField("Jugador");
		avaliable.setFont(westCenterFont);
		player1.setFont(westCenterFont);
		player2.setFont(westCenterFont);
		player3.setFont(westCenterFont);
		player4.setFont(westCenterFont);
		player5.setFont(westCenterFont);
		player6.setFont(westCenterFont);
		player7.setFont(westCenterFont);
		player8.setFont(westCenterFont);
		player9.setFont(westCenterFont);
		player10.setFont(westCenterFont);
		player11.setFont(westCenterFont);
		player12.setFont(westCenterFont);
		player13.setFont(westCenterFont);
		player14.setFont(westCenterFont);
		player15.setFont(westCenterFont);
		player16.setFont(westCenterFont);
		player17.setFont(westCenterFont);
		player18.setFont(westCenterFont);
		player19.setFont(westCenterFont);
		player20.setFont(westCenterFont);
		player21.setFont(westCenterFont);
		player22.setFont(westCenterFont);
		player23.setFont(westCenterFont);
		player24.setFont(westCenterFont);
		player25.setFont(westCenterFont);
		avaliable.setHorizontalAlignment(SwingConstants.RIGHT);
		initBlank(avaliable);
		initBlank(player1);
		initBlank(player2);
		initBlank(player3);
		initBlank(player4);
		initBlank(player5);
		initBlank(player6);
		initBlank(player7);
		initBlank(player8);
		initBlank(player9);
		initBlank(player10);
		initBlank(player11);
		initBlank(player12);
		initBlank(player13);
		initBlank(player14);
		initBlank(player15);
		initBlank(player16);
		initBlank(player17);
		initBlank(player18);
		initBlank(player19);
		initBlank(player20);
		initBlank(player21);
		initBlank(player22);
		initBlank(player23);
		initBlank(player24);
		initBlank(player25);
		west.add(avaliable);
		west.add(player1);
		west.add(player2);
		west.add(player3);
		west.add(player4);
		west.add(player5);
		west.add(player6);
		west.add(player7);
		west.add(player8);
		west.add(player9);
		west.add(player10);
		west.add(player11);
		west.add(player12);
		west.add(player13);
		west.add(player14);
		west.add(player15);
		west.add(player16);
		west.add(player17);
		west.add(player18);
		west.add(player19);
		west.add(player20);
		west.add(player21);
		west.add(player22);
		west.add(player23);
		west.add(player24);
		west.add(player25);
		return west;
	}
	public JPanel createCenterButtons() {
		JPanel centerButtons = new JPanel(new GridLayout(8,3,0,HEIGHT/50));
		JTextField blank = new JTextField();
		JTextField blank2 = new JTextField();
		JTextField blank3 = new JTextField();
		JTextField blank4 = new JTextField();
		JTextField blank5 = new JTextField();
		JTextField blank6 = new JTextField();
		JTextField blank7 = new JTextField();
		JTextField blank8 = new JTextField();
		JTextField blank9 = new JTextField();
		JTextField blank10 = new JTextField();
		JTextField blank11 = new JTextField();
		JTextField blank12 = new JTextField();
		JTextField blank13 = new JTextField();
		JTextField blank14 = new JTextField();
		JTextField blank15 = new JTextField();
		JTextField blank16 = new JTextField();
		JTextField blank17 = new JTextField();
		JTextField blank18 = new JTextField();
		buyButton.setFont(centerButtonFont);
		sellButton.setFont(centerButtonFont);
		helpButton.setFont(centerButtonFont);
		infoButton.setFont(centerButtonFont);
		exitButton.setFont(centerButtonFont);
		initBlank(blank);
		initBlank(blank2);
		initBlank(blank3);
		initBlank(blank4);
		initBlank(blank5);
		initBlank(blank6);
		initBlank(blank7);
		initBlank(blank8);
		initBlank(blank9);
		initBlank(blank10);
		initBlank(blank11);
		initBlank(blank12);
		initBlank(blank13);
		initBlank(blank14);
		initBlank(blank15);
		initBlank(blank16);
		initBlank(blank17);
		initBlank(blank18);
		centerButtons.add(blank);
		centerButtons.add(blank2);
		centerButtons.add(blank3);
		centerButtons.add(blank4);
		centerButtons.add(buyButton);
		centerButtons.add(blank5);
		centerButtons.add(blank6);
		centerButtons.add(sellButton);
		centerButtons.add(blank7);
		centerButtons.add(blank8);
		centerButtons.add(blank9);
		centerButtons.add(blank10);
		centerButtons.add(blank11);
		centerButtons.add(infoButton);
		centerButtons.add(blank12);
		centerButtons.add(blank13);
		centerButtons.add(helpButton);
		centerButtons.add(blank14);
		centerButtons.add(blank15);
		centerButtons.add(blank16);
		centerButtons.add(blank17);
		centerButtons.add(blank18);
		centerButtons.add(exitButton);
		buyButton.addActionListener(this);
		sellButton.addActionListener(this);
		infoButton.addActionListener(this);
		helpButton.addActionListener(this);
		exitButton.addActionListener(this);
		return centerButtons;
	}
	public void createSouth() {
		JPanel south = new JPanel(new GridLayout(2,3,WIDTH/100,0));
		JTextField lastAction = new JTextField();
		JTextField lastActionName = new JTextField();
		JTextField blank = new JTextField();
		JTextField blank2 = new JTextField();
		JTextField blank3 = new JTextField();
		initBlank(lastAction);
		initBlank(lastActionName);
		initBlank(blank);
		initBlank(blank2);
		initBlank(blank3);
		south.add(blank);
		south.add(blank2);
		south.add(blank3);
		south.add(lastAction);
		south.add(lastActionName);
		add(south,BorderLayout.SOUTH);
	}
	@Override
	public void actionPerformed(ActionEvent e) {
		if(e.getSource()==buyButton) {
			System.out.println("Buy");
		} 
		if(e.getSource()==sellButton) {
			System.out.println("Sell");
		} 
		if(e.getSource()==infoButton) {
			System.out.println("Info");
		} 
		if(e.getSource()==helpButton) {
			System.out.println("Help");
		} 
		if(e.getSource()==exitButton) {
			System.exit(0);
		} 
		
	}
}
